# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build & Publish linux

on: [ workflow_dispatch ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ctp-version: [ "6315", "6319", "651", "661", "667", "669" ]

    steps:
      - uses: actions/checkout@v3
      - name: Checkout openctp-ctp-${{ matrix.ctp-version }}
        uses: actions/checkout@v3
        with:
          repository: Jedore/openctp-ctp-${{ matrix.ctp-version }}
          path: 'openctp-ctp-${{ matrix.ctp-version }}'
      - name: Set up Python
        uses: actions/setup-python@v3
#        with:
#          python-version: ${{ matrix.python-version }}
      - name: Sync files
        run: python templates/sync.py ${{ matrix.ctp-version }}
#      - name: Modify Ubuntu Locale
#        run: |
#          sudo apt-get install -y locales
#          sudo locale-gen zh_CN.GB18030
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Building Package
        working-directory: openctp-ctp-${{ matrix.ctp-version }}
#        run: hatch build -t wheel
        run: |
          export CIBW_REPAIR_WHEEL_COMMAND=
          python -m cibuildwheel --platform linux --config-file pyproject.toml --output-dir ../dist
#      - name: Install Package
#        run: |
#          pip install dist/*.whl
#        shell: bash
#      - name: Test
#        run: |
#          pytest --ctp 6315 tests
      - name: Store Package
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distribution
          path: dist


#  build-windows:
#    runs-on: windows-2019
#    strategy:
#      matrix:
#        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
#
#    steps:
#      - name: Checkout openctp-ctp-python
#        uses: actions/checkout@v3
#      - name: Checkout openctp-ctp-6315
#        uses: actions/checkout@v3
#        with:
#          repository: Jedore/openctp-ctp-6315
#          path: openctp-ctp-6315
#      - name: Set up Python
#        uses: actions/setup-python@v3
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Sync files
#        run: python templates/sync.py 6315
#      - name: Install dependencies
#        run: |
#          pip install -r requirements.txt
#      - name: Building Package
#        working-directory: openctp-ctp-6315
#        run: hatch build -t wheel
#      - name: Install Package
#        run: |
#          pip install dist/*.whl
#        shell: bash
#      - name: Test
#        run: |
#          pytest --ctp 6315 tests
#      - name: Store Package
#        uses: actions/upload-artifact@v3
#        with:
#          name: python-package-distribution
#          path: dist


  publish-wheel:
    needs:
      - build-linux
#      - build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install hatch
      - name: Download Package
        uses: actions/download-artifact@v3
        with:
          name: python-package-distribution
          path: dist/
      - name: Publish a Python distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
#          repository-url: https://test.pypi.org/legacy/

#  test-linux:
#    needs:
#      - publish-wheel
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
#
#    steps:
#      - name: Checkout openctp-ctp-python
#        uses: actions/checkout@v3
#      - name: Set up Python
#        uses: actions/setup-python@v3
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Modify Ubuntu Locale
#        run: |
#          sudo apt-get install -y locales
#          sudo locale-gen zh_CN.GB18030
#      - name: Install dependencies
#        run: |
#          pip install -r requirements.txt
#      - name: Install Package
#        run: |
#          pip install -i https://test.pypi.org/simple/ openctp-ctp-6315
#        shell: bash
#      - name: Test
#        run: |
#          pytest --ctp 6315 tests


#  test-windows:
#    needs:
#      - publish-wheel
#    runs-on: windows-latest
#    strategy:
#      matrix:
#        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
#
#    steps:
#      - name: Checkout openctp-ctp-python
#        uses: actions/checkout@v3
#      - name: Set up Python
#        uses: actions/setup-python@v3
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Install dependencies
#        run: |
#          pip install -r requirements.txt
#      - name: Install Package
#        run: |
#          pip install -i https://test.pypi.org/simple/ openctp-ctp-6315
#        shell: bash
#      - name: Test
#        run: |
#          pytest --ctp 6315 tests
